An error occurred while executing the following cell:
------------------
import jax.numpy as jnp
from jax.experimental import optimizers
import jax

try:
    import jax_bayes
except ModuleNotFoundError:
    %pip install -qq jax_bayes
    import jax_bayes

try:
    import sys, os, math, time
except ModuleNotFoundError:
    %pip install -qq sys,
    import sys, os, math, time
import numpy as np
from functools import partial
from matplotlib import pyplot as plt

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"
try:
    import tensorflow_datasets as tfds
except ModuleNotFoundError:
    %pip install -qq tensorflow tensorflow_datasets
    import tensorflow_datasets as tfds
------------------

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_3647/3659454802.py in <module>
     21 try:
---> 22     import tensorflow_datasets as tfds
     23 except ModuleNotFoundError:

ModuleNotFoundError: No module named 'tensorflow_datasets'

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
/tmp/ipykernel_3647/3659454802.py in <module>
     23 except ModuleNotFoundError:
     24     get_ipython().run_line_magic('pip', 'install -qq tensorflow tensorflow_datasets')
---> 25     import tensorflow_datasets as tfds

~/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow_datasets/__init__.py in <module>
     41 # needs to happen before anything else, since the imports below will try to
     42 # import tensorflow, too.
---> 43 from tensorflow_datasets.core import tf_compat
     44 tf_compat.ensure_tf_install()
     45 

~/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow_datasets/core/__init__.py in <module>
     20 from tensorflow_datasets.core import tf_compat
     21 
---> 22 tf_compat.ensure_tf_install()
     23 
     24 # pylint:disable=g-import-not-at-top

~/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow_datasets/core/tf_compat.py in ensure_tf_install()
     46 
     47   try:
---> 48     import tensorflow as tf  # pylint: disable=import-outside-toplevel
     49   except ImportError:
     50     # Print more informative error message, then reraise.

~/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/__init__.py in <module>
     35 import typing as _typing
     36 
---> 37 from tensorflow.python.tools import module_util as _module_util
     38 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader
     39 

~/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/__init__.py in <module>
     34 # pylint: disable=wildcard-import,g-bad-import-order,g-import-not-at-top
     35 
---> 36 from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
     37 from tensorflow.python.eager import context
     38 

~/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>
     24 
     25 # Perform pre-load sanity checks in order to produce a more actionable error.
---> 26 self_check.preload_check()
     27 
     28 # pylint: disable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

~/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/platform/self_check.py in preload_check()
     63     cpu_feature_guard_library = os.path.join(
     64         os.path.dirname(__file__), "../../core/platform/_cpu_feature_guard.so")
---> 65     ctypes.CDLL(cpu_feature_guard_library)

~/miniconda3/envs/py37/lib/python3.7/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: /github/home/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/platform/../../core/platform/_cpu_feature_guard.so: cannot open shared object file: No such file or directory
OSError: /github/home/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/platform/../../core/platform/_cpu_feature_guard.so: cannot open shared object file: No such file or directory
