An error occurred while executing the following cell:
------------------
try:
    import sys, os
except ModuleNotFoundError:
    %pip install -qq sys,
    import sys, os
try:
    import torch
except ModuleNotFoundError:
    %pip install -qq torch
    import torch
try:
    from torchvision.datasets import CelebA, MNIST
except ModuleNotFoundError:
    %pip install -qq torchvision
    from torchvision.datasets import CelebA, MNIST
import torchvision.transforms as transforms

try:
    from pytorch_lightning import LightningDataModule, LightningModule, Trainer
except ModuleNotFoundError:
    %pip install -qq pytorch_lightning
    from pytorch_lightning import LightningDataModule, LightningModule, Trainer
from torch.utils.data import DataLoader, random_split, SequentialSampler, RandomSampler
import numpy as np
from matplotlib import pyplot as plt

try:
    from imageio import imwrite
except ModuleNotFoundError:
    %pip install -qq imageio
    from imageio import imwrite
from packaging import version

try:
    from tqdm import tqdm
except ModuleNotFoundError:
    %pip install -qq tqdm
    from tqdm import tqdm
try:
    from data import CelebADataset, CelebADataModule
except ModuleNotFoundError:
    %pip install -qq data
    from data import CelebADataset, CelebADataModule
try:
    from mfa_celeba_helpers import *
except ModuleNotFoundError:
    %pip install -qq mfa_celeba_helpers
    from mfa_celeba_helpers import *
from IPython.display import Image


def main(argv):
    assert version.parse(torch.__version__) >= version.parse("1.2.0")

    dataset = argv[1] if len(argv) == 2 else "celeba"
    print("Preparing dataset and parameters for", dataset, "...")

    if dataset == "celeba":
        image_shape = [64, 64, 3]  # The input image shape
        n_components = 300  # Number of components in the mixture model
        n_factors = 10  # Number of factors - the latent dimension (same for all components)
        batch_size = 1000  # The EM batch size
        num_iterations = 30  # Number of EM iterations (=epochs)
        feature_sampling = 0.2  # For faster responsibilities calculation, randomly sample the coordinates (or False)
        mfa_sgd_epochs = 0  # Perform additional training with diagonal (per-pixel) covariance, using SGD
        init_method = "rnd_samples"  # Initialize each component from few random samples using PPCA
        trans = transforms.Compose(
            [
                CropTransform((25, 50, 25 + 128, 50 + 128)),
                transforms.Resize(image_shape[0]),
                transforms.ToTensor(),
                ReshapeTransform([-1]),
            ]
        )
        train_set = CelebADataset(root="./data", split="train", transform=trans, download=True)
        test_set = CelebADataset(root="./data", split="test", transform=trans, download=True)

    elif dataset == "mnist":
        image_shape = [28, 28]  # The input image shape
        n_components = 50  # Number of components in the mixture model
        n_factors = 6  # Number of factors - the latent dimension (same for all components)
        batch_size = 1000  # The EM batch size
        num_iterations = 1  # Number of EM iterations (=epochs)
        feature_sampling = False  # For faster responsibilities calculation, randomly sample the coordinates (or False)
        mfa_sgd_epochs = 0  # Perform additional training with diagonal (per-pixel) covariance, using SGD
        init_method = "kmeans"  # Initialize by using k-means clustering
        trans = transforms.Compose([transforms.ToTensor(), ReshapeTransform([-1])])
        train_set = MNIST(root="./data", train=True, transform=trans, download=True)
        test_set = MNIST(root="./data", train=False, transform=trans, download=True)
    else:
        assert False, "Unknown dataset: " + dataset
------------------

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_4722/4106335031.py in <module>
     18 try:
---> 19     from pytorch_lightning import LightningDataModule, LightningModule, Trainer
     20 except ModuleNotFoundError:

ModuleNotFoundError: No module named 'pytorch_lightning'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_4722/4106335031.py in <module>
     20 except ModuleNotFoundError:
     21     get_ipython().run_line_magic('pip', 'install -qq pytorch_lightning')
---> 22     from pytorch_lightning import LightningDataModule, LightningModule, Trainer
     23 from torch.utils.data import DataLoader, random_split, SequentialSampler, RandomSampler
     24 import numpy as np

~/miniconda3/envs/py37/lib/python3.7/site-packages/pytorch_lightning/__init__.py in <module>
     32     _logger.propagate = False
     33 
---> 34 from pytorch_lightning.callbacks import Callback  # noqa: E402
     35 from pytorch_lightning.core import LightningDataModule, LightningModule  # noqa: E402
     36 from pytorch_lightning.trainer import Trainer  # noqa: E402

~/miniconda3/envs/py37/lib/python3.7/site-packages/pytorch_lightning/callbacks/__init__.py in <module>
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from pytorch_lightning.callbacks.callback import Callback
     15 from pytorch_lightning.callbacks.checkpoint import Checkpoint
     16 from pytorch_lightning.callbacks.device_stats_monitor import DeviceStatsMonitor

~/miniconda3/envs/py37/lib/python3.7/site-packages/pytorch_lightning/callbacks/callback.py in <module>
     23 
     24 import pytorch_lightning as pl
---> 25 from pytorch_lightning.utilities.types import STEP_OUTPUT
     26 
     27 

~/miniconda3/envs/py37/lib/python3.7/site-packages/pytorch_lightning/utilities/__init__.py in <module>
     16 import numpy
     17 
---> 18 from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
     19 from pytorch_lightning.utilities.distributed import AllGatherGrad  # noqa: F401
     20 from pytorch_lightning.utilities.enums import (  # noqa: F401

~/miniconda3/envs/py37/lib/python3.7/site-packages/pytorch_lightning/utilities/apply_func.py in <module>
     27 
     28 from pytorch_lightning.utilities.exceptions import MisconfigurationException
---> 29 from pytorch_lightning.utilities.imports import _compare_version, _TORCHTEXT_LEGACY
     30 from pytorch_lightning.utilities.warnings import rank_zero_deprecation
     31 

~/miniconda3/envs/py37/lib/python3.7/site-packages/pytorch_lightning/utilities/imports.py in <module>
     20 from typing import Callable
     21 
---> 22 import pkg_resources
     23 import torch
     24 from packaging.version import Version

ModuleNotFoundError: No module named 'pkg_resources'
ModuleNotFoundError: No module named 'pkg_resources'
