An error occurred while executing the following cell:
------------------
try:
    import probml_utils.mnist_helper_tf as helper
except ModuleNotFoundError:
    %pip install -qq git+https://github.com/probml/probml-utils.git
    import probml_utils.mnist_helper_tf as helper
------------------

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_3973/2619592856.py in <module>
      1 try:
----> 2     import probml_utils.mnist_helper_tf as helper
      3 except ModuleNotFoundError:

ModuleNotFoundError: No module named 'probml_utils'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_3973/2619592856.py in <module>
      3 except ModuleNotFoundError:
      4     get_ipython().run_line_magic('pip', 'install -qq git+https://github.com/probml/probml-utils.git')
----> 5     import probml_utils.mnist_helper_tf as helper

ModuleNotFoundError: No module named 'probml_utils'
ModuleNotFoundError: No module named 'probml_utils'
